services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (Nginx)
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    restart: always
    environment:
      MONGODB_URI: mongodb://mongo:27017/online_exam_platform
      PORT: 5000
      JWT_SECRET: your_jwt_secret_key_here # IMPORTANT: Change this in a .env file or your actual deployment configuration
      # NODE_ENV: development # or production
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
